services:
  backend:
    build:
      context: ./backend
    image: website-devops-backend:latest
    ports:
      - "${API_PORT}:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mysql
    command: ["wait-for-it", "mysql:3306", "--", "yarn", "start"]
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./set_database:/docker-entrypoint-initdb.d
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: website-devops-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge