services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projet_k8s
    depends_on:
      - mysql
    command: ["wait-for-it", "mysql:3306", "--", "yarn", "start"]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_k8s
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql-data:
    driver: local
